config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get '/about', to: "pages#about"
  get 'wallets/index'
  resources :wallets do 
    collection do
      get :main_page
    end

    member do 
      get :symbolings
      get :notifications
      get :symbol_end_of_day_data
    end
  end

  resources :symbolings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :wallet

  def self.wallet_message(symboling_name, threshold)
    "The close price of #{symboling_name} is greater than #{threshold}"
  end
end

app/models/symboling.rb
class Symboling < ApplicationRecord
  belongs_to :wallet
  validates :name, presence: true, uniqueness: { scope: :wallet_id, message: ": Symbole name already Exist in this wallet"}
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  has_many :symbolings, dependent: :destroy
  has_many :notifications, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/symbolings_controller.rb
require "#{Rails.root}/app/services/marketstack_service.rb"
class SymbolingsController < ApplicationController
  before_action :set_symboling, only: %i[ destroy ]

  def update
    @symboling = Symboling.find_by(id: params[:id])
    symbol_info = MarketstackService.get_data("eod", params[:symboling][:name])
    return render json: { message: MarketstackService.parse_error_message(symbol_info), status: "failed" } if symbol_info.keys.include?("error")
    if @symboling.update(symboling_params)
      render json: { symboling: @symboling, status: "succeeded"}
    else
      render json: { status: "failed", message: @symboling.errors.full_messages }
    end
  end

  def create 
    @symboling = Symboling.new(symboling_params)
    symbol_info = MarketstackService.get_data("eod", params[:symboling][:name])
    return render json: { message: MarketstackService.parse_error_message(symbol_info), status: "failed" } if symbol_info.keys.include?("error")
    
    if @symboling.save
      close_price = symbol_info["data"].first["close"]
      Notification.create(wallet: @symboling.wallet, content: Notification.wallet_message(@symboling.name, 70)) if close_price > 70
      render json: { symboling: @symboling, status: "succeeded" }
    else
      render json: { message: @symboling.errors.full_messages, status: "failed" }
    end
  end

  def destroy
    @symboling.destroy
    render json: { status: "succeeded" }
  end

  private

  def set_symboling
    @symboling = Symboling.find_by(id: params[:id])
    return render json: { message: "Record not found", status: "failed" } unless @symboling
  end
  
  def symboling_params
    params.require(:symboling).permit(:name, :wallet_id)
  end
end

app/controllers/wallets_controller.rb
require "#{Rails.root}/app/services/marketstack_service.rb"
class WalletsController < ApplicationController
  before_action :set_wallet, only: %i[ update destroy symbolings notifications symbol_end_of_day_data]
  
  def index
    render json: Wallet.all.order(id: :desc)
  end

  def main_page
  end

  def symbol_end_of_day_data
    symboling_string = @wallet.symbolings.map(&:name).join(",")
    symbol_info = MarketstackService.get_data("eod", symboling_string)["data"].shuffle[0,6]
    render json: symbol_info
  end

  def symbolings
    @symbols = @wallet.symbolings
    render json: @wallet.symbolings
  end

  def notifications
    render json: @wallet.notifications.order(id: :desc)
  end

  def update
    if @wallet.update(wallet_params)
      render json: { wallet: @wallet, status: "succeeded" }
    else
      render json: { message: @wallet.errors.messages, status: "failed" }
    end
  end

  def create
    @wallet = Wallet.new(wallet_params)
    if @wallet.save
      render json: {wallet: @wallet, status: "succeeded"}
    else
      render json: { message: @wallet.errors.full_messages, status: "failed" }
    end
  end
  
  private

  def wallet_params
    params.require(:wallet).permit(:name)
  end

  def set_wallet
    @wallet = Wallet.find_by(id: params[:id])
    return render json: { message: "Record not found", status: "failed" } unless @wallet
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/symbolings_helper.rb
module SymbolingsHelper
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockExchangeMarketRoy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" unless params[:action] == "home" %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="contaienr p5">
  <h1 class="text-center mt-5 py-5 text-white">Nyaga Andre Roy</h1>
</div>

app/views/pages/home.html.erb
<div class="container-fluid p-0" id="home-page-wrapper">
  <%=render "shared/navbar" %>
  <div class="home-page-button-div d-flex justify-content-center align-items-center">
    <div>
      <span class="m-3"><%=link_to "About Us", about_path, class: "general-buttons" %></span>
      <span class="m-3"><%= link_to "Get Started", main_page_wallets_path, class: "general-buttons"%></span>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav id="navbar-div" class="py-4">
  <div class="d-flex justify-content-center">
    <span><%= link_to "Home", root_path, class: "general-buttons m-2" %></span>
    <span><%=link_to "About", about_path, class: "general-buttons m-2" %></span>
    <span><%= link_to "Wallet", main_page_wallets_path, class: "general-buttons m-2" %></span>
  </div>
</nav>

app/views/wallets/main_page.html.erb
<%= react_component("pages/wallets/walletPage")%>